import { Alien } from '../interface/alien.interface';


export const aliens:Alien[] = [
    {
      name: "Carl Stuard",
      humanImg: "/img/alien001.webp",
      alienImg: "/img/alien002.webp",
      origin: "Polo, Centurion IV",
      city: "Boston EU",
      reward: "500",
      danger: "Nivel 7",
      planetImg: "https://example.com/planet-centurion.jpg",
      planet: "Centurion IV",
      system: "Sistema Andrómeda",
      species: "Armudariano",
      description:
        "Carl Stuard es un fugitivo intergaláctico buscado por múltiples crímenes cometidos en distintos sistemas estelares. Es conocido por su inteligencia estratégica y habilidades para disfrazarse entre humanos. Los Armudarianos poseen la capacidad de mimetizarse y manipular campos energéticos, lo que los hace especialmente peligrosos.",
      crimes: [
        { year: "2018", description: "Robo de tecnología avanzada en la base científica de la NASA en Houston." },
        { year: "2019", description: "Destrucción parcial de una nave comercial intergaláctica cerca de Proxima Centauri." },
        { year: "2020", description: "Secuestro de un científico humano especializado en energía cuántica." },
        { year: "2021", description: "Tráfico ilegal de cristales energéticos en el Sistema Vega." },
        { year: "2022", description: "Intento de sabotaje de un acuerdo de paz entre el Consejo Galáctico y los habitantes de Alpha Centauri." },
      ],
    },
    {
      name: "Yoka Chronis",
      humanImg: "/img/alien011.webp",
      alienImg: "/img/alien012.webp",
      origin: "Orbitaris IX, Zorathia",
      city: "Las Vegas, EU",
      reward: "750",
      danger: "Nivel 9",
      planetImg: "https://example.com/planet-delta9.jpg",
      planet: "Orbitaris IX",
      system: "Zorathia",
      species: "Aquarion Luminaris",
      description:
      "Exiliado por Rebelión: Yoka lideró una facción de su especie en contra del consejo de Orbitaris IX, en desacuerdo con las estrictas leyes de aislamiento del planeta. Este acto de rebeldía resultó en su exilio, forzándolo a buscar refugio entre las estrellas.",
      crimes: [
        { year: "2015", description: "Liberación de un virus alienígena en una colonia humana en Marte." },
        { year: "2016", description: "Extorsión al embajador galáctico de Tau Ceti." },
        { year: "2018", description: "Ataque bioterrorista en la estación espacial Nexus IV." },
        { year: "2020", description: "Contrabando de armas bioquímicas hacia la Tierra." },
        { year: "2021", description: "Manipulación genética ilegal de especies terrestres." },
      ],
    },
    {
      name: "Zynthar Drakthon",
      humanImg: "/img/alien021.webp",
      alienImg: "/img/alien022.webp",
      origin: "Pyroxia Prime, Sistema Ignarion",
      city: "París, Francia",
      reward: "600",
      danger: "Nivel 8",
      planetImg: "https://example.com/planet-syrris.jpg",
      planet: "Pyroxia Prime",
      system: "Sistema Ignarion",
      species: "Ignisphoriano",
      description:
        "ynthar fue un general respetado en el ejército Pyroxiano, pero su decisión de priorizar una misión de rescate sobre un ataque estratégico lo llevó a ser degradado. Este acto lo convirtió en un héroe para algunos y en un traidor para otros.",
      crimes: [
        { year: "2017", description: "Robo de secretos militares en el Pentágono." },
        { year: "2018", description: "Destrucción de una planta de energía en Júpiter." },
        { year: "2019", description: "Espionaje en el Consejo Galáctico." },
        { year: "2021", description: "Sabotaje de la misión espacial Apolo-Nova." },
        { year: "2023", description: "Control mental de líderes mundiales para influir en políticas globales." },
      ],
    },
    {
      name: "Gorlok Luminae",
      humanImg: "/img/alien031.webp",
      alienImg: "/img/alien032.webp",
      origin: "Luminara VII, Sistema Sirius",
      city: "Tokio, Japón",
      reward: "850",
      danger: "Nivel 10",
      planetImg: "https://example.com/planet-gorath.jpg",
      planet: "Luminara VII",
      system: "Sirius",
      species: "Noctiluminae",
      description:
        "Gorlok era un protector de los bosques bioluminiscentes de Luminara, pero fue traicionado por su propio consejo cuando intentaron sacrificar parte del ecosistema para ganar poder político.",
      crimes: [
        { year: "2016", description: "Asesinato de un diplomático en la Luna de Io." },
        { year: "2017", description: "Destrucción de un satélite galáctico estratégico." },
        { year: "2018", description: "Secuestro de un grupo de colonos espaciales en Titán." },
        { year: "2019", description: "Extorsión masiva a colonias en el Sistema Solar." },
        { year: "2022", description: "Intento de golpe de estado en la Alianza Estelar." },
      ],
    },
    {
      name: "Nyssa Callayen",
      humanImg: "/img/alien041.webp",
      alienImg: "/img/alien042.webp",
      origin: "Xerthion Beta, Sistema Altair",
      city: "Ciudad de México, México",
      reward: "400",
      danger: "Nivel 6",
      planetImg: "https://example.com/planet-yzara.jpg",
      planet: "Xerthion Beta",
      system: "Altair",
      species: "Arenomorfo",
      description:
        "Nyssa fue una saqueadora que buscaba artefactos antiguos en Xerthion Beta, pero un incidente lo expuso a un campo magnético que destruyó parte de su cuerpo y lo obligó a buscar ayuda fuera de su planeta.",
      crimes: [
        { year: "2015", description: "Venta de información clasificada del Consejo Galáctico." },
        { year: "2017", description: "Robo de datos de la base estelar Andrómeda II." },
        { year: "2019", description: "Difusión de propaganda falsa en el Sistema Orion." },
        { year: "2021", description: "Falsificación de identidades estelares." },
        { year: "2023", description: "Coordinación de una red de espionaje en la Tierra." },
      ],
    },
  ];


